# Generated by Django 3.0.3 on 2020-06-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForbiddenIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forbiddenIP', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
