# Generated by Django 3.0.3 on 2020-06-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_distancelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfLoginsLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofLogins', models.IntegerField(blank=True, default=5, null=True)),
            ],
        ),
    ]
