# Generated by Django 3.0.3 on 2020-06-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corelogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='phonenumber',
            field=models.CharField(default=None, max_length=17, null=True),
        ),
    ]
