# Generated by Django 3.0.3 on 2020-05-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corelogin', '0002_auto_20200507_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='phonenumber',
            field=models.CharField(blank=True, default=None, max_length=17, null=True),
        ),
    ]
